name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this homebrew tap repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        run: |
          LATEST_VERSION=${{ github.event.release.tag_name }}
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV

      - name: Download binaries
        run: |
          wget -O tempesta-x86_64.tar.gz https://github.com/x71c9/tempesta/releases/download/${LATEST_VERSION}/tempesta-x86_64-apple-darwin.tar.gz
          wget -O tempesta-aarch64.tar.gz https://github.com/x71c9/tempesta/releases/download/${LATEST_VERSION}/tempesta-aarch64-apple-darwin.tar.gz

      - name: Compute SHA256
        run: |
          SHA256_X86_64=$(sha256sum tempesta-x86_64.tar.gz | awk '{print $1}')
          SHA256_AARCH64=$(sha256sum tempesta-aarch64.tar.gz | awk '{print $1}')
          echo "SHA256_X86_64=${SHA256_X86_64}" >> $GITHUB_ENV
          echo "SHA256_AARCH64=${SHA256_AARCH64}" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          sed -i "s|version \".*\"|version \"${LATEST_VERSION#v}\"|" Formula/tempesta.rb
          sed -i "s|url \".*x86_64.*\"|url \"https://github.com/x71c9/tempesta/releases/download/${LATEST_VERSION}/tempesta-x86_64-apple-darwin.tar.gz\"|" Formula/tempesta.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256_X86_64}\"|" Formula/tempesta.rb
          sed -i "s|url \".*aarch64.*\"|url \"https://github.com/x71c9/tempesta/releases/download/${LATEST_VERSION}/tempesta-aarch64-apple-darwin.tar.gz\"|" Formula/tempesta.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256_AARCH64}\"|" Formula/tempesta.rb

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/tempesta.rb
          git commit -m "Update tempesta to ${LATEST_VERSION}"
          git push

